-- [플레이스홀더] 원격 DB 히스토리 동기화용 (no-op)
-- 이 버전(20260527073839)은 원격 DB에 직접(대시보드 SQL 등) 적용되어 schema_migrations 에는 기록돼 있으나
-- 로컬에는 원본 SQL 파일이 남아 있지 않았다. 그 결과 `supabase db push` 가 "remote migration versions not
-- found in local" 가드에 걸려 이후 마이그레이션을 적용하지 못했다.
-- 이 파일은 로컬/원격 히스토리를 일치시키기 위한 빈(no-op) 플레이스홀더이며, 이미 원격 히스토리에
-- 존재하는 버전이라 push 시 재실행되지 않는다. 실제 스키마 변경은 원격에 이미 반영돼 있다.
-- (해당 시점 변경 추정: 강의 'pre_alert' 유형 추가 등 — commit fa32019 참고)
